# **Pandas**

In [1]:
import pandas as pd

## **01 importing data set**

In [5]:
# get the data from Github repository - file - raw 

df = pd.read_csv("https://raw.githubusercontent.com/Sudhakarcs77/DataSets/main/titanic_train")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
#df.shape[0] # no of datapoints
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
type(df.dtypes)   # Series in pandas ~ list in python

pandas.core.series.Series

In [12]:
type(df.columns)

pandas.core.indexes.base.Index

In [13]:
dt = df.dtypes
dt  # dt is pandas series

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [14]:
dt['Pclass']

dtype('int64')

In [15]:
# lets

li = [1,2,5,6,8]
li[2]

5

In [17]:
dt[0:4]  # same task in list


PassengerId     int64
Survived        int64
Pclass          int64
Name           object
dtype: object

In [19]:
dt[0:100:2]

PassengerId     int64
Pclass          int64
Sex            object
SibSp           int64
Ticket         object
Cabin          object
dtype: object

In [20]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [21]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [22]:
type(df["Age"])   # one column is Series

pandas.core.series.Series

In [24]:
#age 5th to 100

df["Age"][10:101]


10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
       ... 
96     71.0
97     23.0
98     34.0
99     34.0
100    28.0
Name: Age, Length: 91, dtype: float64

In [25]:
# rev dir

df["Age"][::-1]

890    32.0
889    26.0
888     NaN
887    19.0
886    27.0
       ... 
4      35.0
3      35.0
2      26.0
1      38.0
0      22.0
Name: Age, Length: 891, dtype: float64

In [26]:
df["Age"][-1]   # -ve index not exists in pd series which exists in list

KeyError: ignored

In [30]:
list(df["Age"][::100])

[22.0, 28.0, 28.0, nan, 39.0, 17.0, 24.0, 18.0, 34.0]

In [32]:
dt

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [31]:
df.describe()  # u get basic stats of numerical features 
# missing values at Age
# avg age 29.6 & avg Fare is 32.2


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [33]:
# filter out cat features

df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## **02 Filter Categorical Features**

In [40]:
df.dtypes[df.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [41]:
df.dtypes[df.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [42]:
df[df.dtypes[df.dtypes == "object"].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [43]:
df_cat = df[df.dtypes[df.dtypes == "object"].index]

In [45]:
df_cat.describe()

# so many data points missing for Cabin 
# all names unique


Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [46]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [48]:
df['Name','Age']

KeyError: ignored

In [50]:
df[['Name','Age']].head()

Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [51]:
type(df[['Name','Age']]) # Data Frame not Series

pandas.core.frame.DataFrame

In [52]:
df['Age'].isnull()  # Find records where null values in age

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [53]:
df['Age'].isnull()==True

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [54]:
import numpy as np

In [55]:
np.where(df['Age'].isnull()==True)  #indexes where null values for age

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888]),)

In [56]:
df[df['Age'].isnull()==True]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [57]:
df_age_null = np.where(df['Age'].isnull()==True)

In [58]:
type(df_age_null)

tuple

In [59]:
df_age_null

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888]),)

## **03 filter based on row values**

In [61]:
df.iloc[df_age_null]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [62]:
df.iloc[5]  # gives u series

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [63]:
type(df.iloc[5])

pandas.core.series.Series

In [64]:
df.iloc[[1,2,3,5,8]]   # iloc looks for index number

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
5            6         0       3   
8            9         1       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                                   Moran, Mr. James    male   NaN      0   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
5      0            330877   8.4583   NaN        Q  
8      2            347742  11.1333   NaN        S

## **04 person name who paid highest Fair**

In [70]:
np.where(df['Fare'] == max(df['Fare']))

(array([258, 679, 737]),)

In [73]:
df.iloc[np.where(df['Fare'] == max(df['Fare']))]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [77]:
df[df['Fare'] == max(df['Fare'])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [78]:
df[df['Fare'] == max(df['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

## **05 Person name Whose Age is 25 years**


In [82]:
df[df['Age'] == 25]['Name']

75                             Moen, Mr. Sigurd Hansen
134                     Sobey, Mr. Samuel James Hayden
246              Lindahl, Miss. Agda Thorilda Viktoria
267                           Persson, Mr. Ernst Ulrik
271                       Tornquist, Mr. William Henry
343         Sedgwick, Mr. Charles Frederick Waddington
353                          Arnold-Franchi, Mr. Josef
370                        Harder, Mr. George Achilles
442                          Petterson, Mr. Johan Emil
484                            Bishop, Mr. Dickinson H
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
580                        Christy, Miss. Julie Rachel
666                        Butler, Mr. Reginald Fenton
685             Laroche, Mr. Joseph Philippe Lemercier
693                                   Saad, Mr. Khalil
703                              Gallagher, Mr. Martin
728                    Bryhl, Mr. Kurt Arnold Gottfrid
729                      Ilmakangas, Miss. Pieta Sofia
784       

In [87]:
df[df['Age'] == df['Age'].min()][['Name','Age']]

Name   Age
803  Thomas, Master. Assad Alexander  0.42

In [88]:
df[df['Age'] == df['Age'].max()][['Name','Age']]

Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0

## **06 Age of a person whose cabin is NaN**

In [94]:
df[df['Cabin'].isnull()==True]['Age']

0      22.0
2      26.0
4      35.0
5       NaN
7       2.0
       ... 
884    25.0
885    39.0
886    27.0
888     NaN
890    32.0
Name: Age, Length: 687, dtype: float64

In [95]:
np.where(df['Cabin'].isnull()==True)

(array([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,  15,  16,  17,
         18,  19,  20,  22,  24,  25,  26,  28,  29,  30,  32,  33,  34,
         35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
         48,  49,  50,  51,  53,  56,  57,  58,  59,  60,  63,  64,  65,
         67,  68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,
         81,  82,  83,  84,  85,  86,  87,  89,  90,  91,  93,  94,  95,
         98,  99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112,
        113, 114, 115, 116, 117, 119, 120, 121, 122, 125, 126, 127, 129,
        130, 131, 132, 133, 134, 135, 138, 140, 141, 142, 143, 144, 145,
        146, 147, 149, 150, 152, 153, 154, 155, 156, 157, 158, 159, 160,
        161, 162, 163, 164, 165, 167, 168, 169, 171, 172, 173, 175, 176,
        178, 179, 180, 181, 182, 184, 186, 187, 188, 189, 190, 191, 192,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 206, 207, 208, 210,
        211, 212, 213, 214, 216, 217, 219, 220, 221

In [101]:
df.iloc[np.where(df['Cabin'].isnull()==True)][['Age','Cabin']]

Age Cabin
0    22.0   NaN
2    26.0   NaN
4    35.0   NaN
5     NaN   NaN
7     2.0   NaN
..    ...   ...
884  25.0   NaN
885  39.0   NaN
886  27.0   NaN
888   NaN   NaN
890  32.0   NaN

[687 rows x 2 columns]

## **07 name of the male passengers who survived**

In [102]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [109]:
df[ (df['Survived']==1) & (df['Sex'] == 'male')] ['Name']    # not use AND

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...               
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis 
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

In [106]:
df[df['Survived']==1][df['Sex'] == 'male']['Name']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...               
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis 
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

In [113]:
df.Name[ (df['Survived'] == 1) & (df['Sex'] == 'male')]

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...               
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis 
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

## **new column**

In [116]:
df["new_col"] = 'Sid'
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  
0        0         A/5 21171   7.2500   NaN        S     Sid  
1        0          PC 17599  71.2833   C85        C     Sid  
2        0  STON/O2. 3101282   7.9250   NaN        S     Sid  
3        0            113803  53.1000  C123        S     Sid  
4        0            373450   8.0500   NaN        S     Sid  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S     Sid  
887      0            112053  30.0000   B42        S     Sid  
888      2        W./C. 6607  23.4500   NaN        S     Sid  
889      0            111369  30.0000  C148        C     Sid  
890      0            370376   7.7500   NaN        Q     Sid  

[891 rows x 13 columns]

In [117]:
li = [1,2,3,4,5]
pd.Series(li)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [118]:
dic = {"key1":"val1",
       "key2":"val2",
       "key3":"val3",
       } 

In [121]:
# convert dict to DF

pd.DataFrame(dic,index=[1,2,3])

key1  key2  key3
1  val1  val2  val3
2  val1  val2  val3
3  val1  val2  val3

In [122]:
pd.Series(dic)

key1    val1
key2    val2
key3    val3
dtype: object

In [123]:
arr = np.random.randn(3,4)
pd.DataFrame(arr)

0         1         2         3
0 -0.840786 -1.759522  0.874391  0.185250
1 -0.073657 -1.432698 -1.192422  0.749970
2 -0.445258 -1.632474 -0.401542 -0.484912

In [124]:
pd.Series(arr)

ValueError: ignored

In [125]:
pd.Series(np.array([4,5,6,7,8,9]))

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64

In [127]:
series01 = pd.Series(np.array([4,5,6,7,8,9]),index = ['a','b','c','d','e','f'])

In [129]:
series01['c']

6

In [131]:
series01.iloc['a']

TypeError: ignored

In [132]:
series01.iloc[1]

5

In [133]:
series01.loc['a']

4

In [135]:
ser1 = pd.Series(np.array([4,5,6,7,8,9]),index = [11,22,33,44,55,66])

In [136]:
ser1

11    4
22    5
33    6
44    7
55    8
66    9
dtype: int64

In [140]:
ser1.iloc[33] #default index always start from 0
# iloc take default indexes only

IndexError: ignored

In [141]:
ser1.loc[33]

#loc take index name 

6

In [143]:
np.random.randint(3,6,(4,5))

array([[3, 4, 4, 5, 4],
       [4, 4, 4, 3, 3],
       [5, 5, 3, 3, 4],
       [5, 5, 5, 4, 3]])

In [144]:
pd.DataFrame(np.random.randint(3,6,(4,5)))

0  1  2  3  4
0  4  3  4  3  5
1  5  4  5  5  3
2  4  4  5  5  4
3  5  4  5  3  5

In [161]:
df1 = pd.DataFrame(np.random.randint(3,6,(4,5)),index=['a','b','c','d'],columns=['x','y','z','w','v'])

In [162]:
df1

x  y  z  w  v
a  3  3  3  4  5
b  4  5  4  4  5
c  5  3  4  3  3
d  4  3  5  4  3

In [163]:
df1['x']

a    3
b    4
c    5
d    4
Name: x, dtype: int64

In [164]:
df1.iloc[2:,2:]   # df.iloc[rowindex,colindex,step]

z  w  v
c  4  3  3
d  5  4  3

In [166]:
df1.loc[['c','d'],['z','w']]

z  w
c  4  3
d  5  4

In [167]:
df1["new"] = df1["x"]+df1.y

In [168]:
df1

x  y  z  w  v  new
a  3  3  3  4  5    6
b  4  5  4  4  5    9
c  5  3  4  3  3    8
d  4  3  5  4  3    7

In [169]:
df1.drop('w')

KeyError: ignored

In [170]:
df1.drop('w',axis=1)  # not perminent

x  y  z  v  new
a  3  3  3  5    6
b  4  5  4  5    9
c  5  3  4  3    8
d  4  3  5  3    7

In [171]:
df1

x  y  z  w  v  new
a  3  3  3  4  5    6
b  4  5  4  4  5    9
c  5  3  4  3  3    8
d  4  3  5  4  3    7

In [172]:
df1.drop('w',axis=1,inplace=True)

In [173]:
df1

x  y  z  v  new
a  3  3  3  5    6
b  4  5  4  5    9
c  5  3  4  3    8
d  4  3  5  3    7

In [174]:
df1.drop('d',inplace=True)

In [175]:
df1

x  y  z  v  new
a  3  3  3  5    6
b  4  5  4  5    9
c  5  3  4  3    8

In [6]:
import numpy as np,pandas as pd
np.random.seed(23)
x = pd.DataFrame(np.random.randn(4,5),index=['a','b','c','d'],columns=['x','y','z','w','v'])
x

x         y         z         w         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

## **10 Extract -ve values**

In [7]:
x[x['x']<0]

x         y         z         w         v
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [8]:
x[x<0]

x         y         z         w         v
a       NaN       NaN -0.777619       NaN       NaN
b -1.051082 -0.367548 -1.137460 -1.322148       NaN
c -0.347459       NaN       NaN       NaN -1.043450
d -1.009942       NaN       NaN -1.838068 -0.938769

In [10]:
x.values[x.values<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [14]:
x.loc['b','x']

-1.0510815639071178

## **Row and col name for -ve values**

In [15]:
x

x         y         z         w         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [17]:
x.iloc['a']

x    0.666988
y    0.025813
z   -0.777619
w    0.948634
v    0.701672
Name: a, dtype: float64

In [25]:
x

x         y         z         w         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [34]:
for i in x.index:
  for j in x.columns:
    if x.loc[i,j] < 0:
      print(i,j,x.loc[i,j])

a z -0.7776194131918178
b x -1.0510815639071178
b y -0.3675481161171661
b z -1.1374596907250272
b w -1.3221475225908594
c x -0.34745899102186334
c v -1.0434500017467254
d x -1.0099418765878465
d w -1.8380677677579502
d v -0.9387686311201282


## **12 dropna()**

In [37]:
# Create Data Frame

d = {"k1":[10,20,30,np.NaN],
     "k2":["a","b","c","d"],
     "k3":[np.NaN,100,np.NaN,"h"]}
df02 = pd.DataFrame(d)
df02

k1 k2   k3
0  10.0  a  NaN
1  20.0  b  100
2  30.0  c  NaN
3   NaN  d    h

In [38]:
df02.dropna()

k1 k2   k3
1  20.0  b  100

In [39]:
df02.dropna(axis=1)

k2
0  a
1  b
2  c
3  d

In [40]:
df02

k1 k2   k3
0  10.0  a  NaN
1  20.0  b  100
2  30.0  c  NaN
3   NaN  d    h

In [42]:
df02.dropna(thresh=1)

k1 k2   k3
0  10.0  a  NaN
1  20.0  b  100
2  30.0  c  NaN
3   NaN  d    h

In [43]:
df02.dropna(thresh=2)

k1 k2   k3
0  10.0  a  NaN
1  20.0  b  100
2  30.0  c  NaN
3   NaN  d    h

In [44]:
df02.dropna(thresh=3)

k1 k2   k3
1  20.0  b  100

In [45]:
df02.dropna(thresh=3,axis=1)

k1 k2
0  10.0  a
1  20.0  b
2  30.0  c
3   NaN  d

## **13 fillna()**

In [46]:
 df02

k1 k2   k3
0  10.0  a  NaN
1  20.0  b  100
2  30.0  c  NaN
3   NaN  d    h

In [47]:
df02.fillna(999)

k1 k2   k3
0   10.0  a  999
1   20.0  b  100
2   30.0  c  999
3  999.0  d    h

In [48]:
df02.fillna(df02['k1'].mean())

k1 k2    k3
0  10.0  a  20.0
1  20.0  b   100
2  30.0  c  20.0
3  20.0  d     h

## **14 concat**

In [2]:
import numpy as np
a1 = np.random.randn(3,4)
a1

array([[ 1.79014164, -0.59976138,  1.21271212, -1.55412512],
       [-0.86986017, -0.63646393, -0.62720682,  0.89101822],
       [ 1.79143081,  0.01850389, -0.22388489,  0.46925727]])

In [4]:
a2 = np.random.randn(3,4)
a2

array([[-0.82670464,  0.02859205,  0.13101969,  1.61418635],
       [ 2.21483891,  0.33909193,  0.52491217, -1.63218115],
       [ 1.5443346 , -1.43060248,  0.22588034, -0.38991869]])

In [5]:
a3 = np.random.randn(3,4)
a3

array([[-1.47498644, -1.44626329,  0.52753488, -0.18110929],
       [ 0.88266673,  1.0321496 , -0.38813819,  0.68357592],
       [-1.62339759, -0.00753702,  0.53263796,  1.33296747]])

In [18]:
import pandas as pd
df1 = pd.DataFrame(a1,columns=['a','b','c','d'])
df2 = pd.DataFrame(a2,columns=['a','b','c','d'])
df3 = pd.DataFrame(a3,columns=['a','b','c','d'])

In [9]:
df1

a         b         c         d
0 -1.474986 -1.446263  0.527535 -0.181109
1  0.882667  1.032150 -0.388138  0.683576
2 -1.623398 -0.007537  0.532638  1.332967

In [10]:
df2

a         b         c         d
0 -0.826705  0.028592  0.131020  1.614186
1  2.214839  0.339092  0.524912 -1.632181
2  1.544335 -1.430602  0.225880 -0.389919

In [13]:
df3

a         b         c         d
0 -1.474986 -1.446263  0.527535 -0.181109
1  0.882667  1.032150 -0.388138  0.683576
2 -1.623398 -0.007537  0.532638  1.332967

In [20]:
df4 = pd.concat([df1,df2,df3])
df4

a         b         c         d
0  1.790142 -0.599761  1.212712 -1.554125
1 -0.869860 -0.636464 -0.627207  0.891018
2  1.791431  0.018504 -0.223885  0.469257
0 -0.826705  0.028592  0.131020  1.614186
1  2.214839  0.339092  0.524912 -1.632181
2  1.544335 -1.430602  0.225880 -0.389919
0 -1.474986 -1.446263  0.527535 -0.181109
1  0.882667  1.032150 -0.388138  0.683576
2 -1.623398 -0.007537  0.532638  1.332967

In [24]:
# Data at 0th indexes
df4.loc[0]

a         b         c         d
0  1.790142 -0.599761  1.212712 -1.554125
0 -0.826705  0.028592  0.131020  1.614186
0 -1.474986 -1.446263  0.527535 -0.181109

In [23]:
df4.iloc[0]

a    1.790142
b   -0.599761
c    1.212712
d   -1.554125
Name: 0, dtype: float64

In [25]:
df5 = pd.concat([df1,df2,df3],axis=1)

In [26]:
df5

a         b         c         d         a         b         c  \
0  1.790142 -0.599761  1.212712 -1.554125 -0.826705  0.028592  0.131020   
1 -0.869860 -0.636464 -0.627207  0.891018  2.214839  0.339092  0.524912   
2  1.791431  0.018504 -0.223885  0.469257  1.544335 -1.430602  0.225880   

          d         a         b         c         d  
0  1.614186 -1.474986 -1.446263  0.527535 -0.181109  
1 -1.632181  0.882667  1.032150 -0.388138  0.683576  
2 -0.389919 -1.623398 -0.007537  0.532638  1.332967

In [28]:
df5['a']

a         a         a
0  1.790142 -0.826705 -1.474986
1 -0.869860  2.214839  0.882667
2  1.791431  1.544335 -1.623398

In [29]:
df5.iloc[:,4]

0   -0.826705
1    2.214839
2    1.544335
Name: a, dtype: float64

## **15 Merge**

In [40]:
df1 = pd.DataFrame(a1,columns=['a','b','c','d'])
df2 = pd.DataFrame(a1,columns=['a','b','c','d'],index=[3,4,5])


In [31]:
pd.concat([df1,df2])

a         b         c         d
0  1.790142 -0.599761  1.212712 -1.554125
1 -0.869860 -0.636464 -0.627207  0.891018
2  1.791431  0.018504 -0.223885  0.469257
3 -0.826705  0.028592  0.131020  1.614186
4  2.214839  0.339092  0.524912 -1.632181
5  1.544335 -1.430602  0.225880 -0.389919

In [34]:
pd.concat([df1,df2],axis=1)

a         b         c         d         a         b         c  \
0  1.790142 -0.599761  1.212712 -1.554125       NaN       NaN       NaN   
1 -0.869860 -0.636464 -0.627207  0.891018       NaN       NaN       NaN   
2  1.791431  0.018504 -0.223885  0.469257       NaN       NaN       NaN   
3       NaN       NaN       NaN       NaN -0.826705  0.028592  0.131020   
4       NaN       NaN       NaN       NaN  2.214839  0.339092  0.524912   
5       NaN       NaN       NaN       NaN  1.544335 -1.430602  0.225880   

          d  
0       NaN  
1       NaN  
2       NaN  
3  1.614186  
4 -1.632181  
5 -0.389919

In [35]:
pd.concat([df1,df2],axis=1).fillna(0)

a         b         c         d         a         b         c  \
0  1.790142 -0.599761  1.212712 -1.554125  0.000000  0.000000  0.000000   
1 -0.869860 -0.636464 -0.627207  0.891018  0.000000  0.000000  0.000000   
2  1.791431  0.018504 -0.223885  0.469257  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000 -0.826705  0.028592  0.131020   
4  0.000000  0.000000  0.000000  0.000000  2.214839  0.339092  0.524912   
5  0.000000  0.000000  0.000000  0.000000  1.544335 -1.430602  0.225880   

          d  
0  0.000000  
1  0.000000  
2  0.000000  
3  1.614186  
4 -1.632181  
5 -0.389919

In [38]:
df1

a         b         c         d
0  1.790142 -0.599761  1.212712 -1.554125
1 -0.869860 -0.636464 -0.627207  0.891018
2  1.791431  0.018504 -0.223885  0.469257

In [39]:
df2

a         b         c         d
3 -0.826705  0.028592  0.131020  1.614186
4  2.214839  0.339092  0.524912 -1.632181
5  1.544335 -1.430602  0.225880 -0.389919

In [42]:
pd.merge(df1,df2,on='a')

a       b_x       c_x       d_x       b_y       c_y       d_y
0  1.790142 -0.599761  1.212712 -1.554125 -0.599761  1.212712 -1.554125
1 -0.869860 -0.636464 -0.627207  0.891018 -0.636464 -0.627207  0.891018
2  1.791431  0.018504 -0.223885  0.469257  0.018504 -0.223885  0.469257

## **16 Join**

In [43]:
A = pd.DataFrame({'key':[1,2,4,5,6],
                  'firstName' : ['ram','syam','bhim','ravan','laxman'],
                  'lastName': ['x','y','z','a','b']
}
                 )



In [44]:
B = pd.DataFrame({'key':[1,2,3,7,8],
                  'firstName' : ['Rana','Prabhas','AA','NTR','charan'],
                  'lastName': ['m','l','n','o','p']
}
                 )


In [45]:
A.merge(B,on='key')

key firstName_x lastName_x firstName_y lastName_y
0    1         ram          x        Rana          m
1    2        syam          y     Prabhas          l

In [46]:
A.merge(B,on='key',how='outer')

key firstName_x lastName_x firstName_y lastName_y
0    1         ram          x        Rana          m
1    2        syam          y     Prabhas          l
2    4        bhim          z         NaN        NaN
3    5       ravan          a         NaN        NaN
4    6      laxman          b         NaN        NaN
5    3         NaN        NaN          AA          n
6    7         NaN        NaN         NTR          o
7    8         NaN        NaN      charan          p